"""Export SB3 PPO policy to int8 policy_weights.h for embedded inference."""

from __future__ import annotations

import os

import numpy as np


def _relu(x: np.ndarray) -> np.ndarray:
    return np.maximum(x, 0.0)


def _quantize_weights(w_fp: np.ndarray) -> tuple[np.ndarray, float]:
    """W shape (out, in). Returns int8 W and scale such that W_fp ≈ scale * W_int."""
    max_abs = float(np.max(np.abs(w_fp)))
    if max_abs < 1e-8:
        max_abs = 1e-8
    scale = max_abs / 127.0
    w_q = np.clip(np.round(w_fp / scale), -127, 127).astype(np.int8)
    return w_q, scale


def export_policy_int8(model, header_path: str) -> None:
    policy = model.policy
    extractor = policy.mlp_extractor
    lin1 = extractor.policy_net[0]
    lin2 = extractor.policy_net[2]
    act = policy.action_net

    w1 = lin1.weight.detach().cpu().numpy()
    b1 = lin1.bias.detach().cpu().numpy()
    w2 = lin2.weight.detach().cpu().numpy()
    b2 = lin2.bias.detach().cpu().numpy()
    wa = act.weight.detach().cpu().numpy()
    ba = act.bias.detach().cpu().numpy()

    w1_q, s1 = _quantize_weights(w1)
    w2_q, s2 = _quantize_weights(w2)
    wa_q, sa = _quantize_weights(wa)

    obs_dim = w1.shape[1]
    h1 = w1.shape[0]
    h2 = w2.shape[0]
    n_act = wa.shape[0]

    inv_q = 1.0 / 32767.0

    def c_array_int8(name: str, arr: np.ndarray) -> str:
        flat = arr.flatten(order="C")
        parts = ", ".join(str(int(x)) for x in flat)
        return f"static const int8_t {name}[{flat.size}] = {{ {parts} }};\n"

    def c_array_float(name: str, arr: np.ndarray) -> str:
        flat = arr.flatten(order="C")
        parts = ", ".join(f"{float(x):.9e}f" for x in flat)
        return f"static const float {name}[{flat.size}] = {{ {parts} }};\n"

    os.makedirs(os.path.dirname(header_path) or ".", exist_ok=True)
    with open(header_path, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by export_policy.py — do not edit by hand */\n")
        f.write("#ifndef POLICY_WEIGHTS_H\n#define POLICY_WEIGHTS_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define POLICY_OBS_DIM {obs_dim}\n")
        f.write(f"#define POLICY_H1 {h1}\n")
        f.write(f"#define POLICY_H2 {h2}\n")
        f.write(f"#define POLICY_N_ACTION {n_act}\n\n")
        f.write("#define POLICY_IN_Q 32767\n\n")
        f.write(f"static const float POLICY_INV_IN_Q = {inv_q:.9e}f;\n")
        f.write(f"static const float POLICY_SCALE1 = {s1:.9e}f;\n")
        f.write(f"static const float POLICY_SCALE2 = {s2:.9e}f;\n")
        f.write(f"static const float POLICY_SCALE_OUT = {sa:.9e}f;\n\n")
        f.write(c_array_int8("POLICY_W1", w1_q))
        f.write(c_array_float("POLICY_B1", b1))
        f.write(c_array_int8("POLICY_W2", w2_q))
        f.write(c_array_float("POLICY_B2", b2))
        f.write(c_array_int8("POLICY_WA", wa_q))
        f.write(c_array_float("POLICY_BA", ba))
        f.write("\n#endif\n")

    vec = model.get_env()
    obs = vec.observation_space.sample().astype(np.float32)

    def forward_fp(o: np.ndarray) -> np.ndarray:
        z1 = o @ w1.T + b1
        z1 = _relu(z1)
        z2 = z1 @ w2.T + b2
        z2 = _relu(z2)
        return z2 @ wa.T + ba

    def forward_q(o: np.ndarray) -> np.ndarray:
        xq = np.clip(np.round(o * 32767.0), -32768, 32767).astype(np.int32)
        hidden1 = np.zeros(h1, dtype=np.float64)
        for j in range(h1):
            acc = 0
            for k in range(obs_dim):
                acc += int(w1_q[j, k]) * int(xq[k])
            z = float(acc) * s1 * inv_q + float(b1[j])
            hidden1[j] = max(z, 0.0)
        y1q = np.clip(np.round(hidden1 * 32767.0), -32768, 32767).astype(np.int32)
        hidden2 = np.zeros(h2, dtype=np.float64)
        for j in range(h2):
            acc = 0
            for k in range(h1):
                acc += int(w2_q[j, k]) * int(y1q[k])
            z = float(acc) * s2 * inv_q + float(b2[j])
            hidden2[j] = max(z, 0.0)
        y2q = np.clip(np.round(hidden2 * 32767.0), -32768, 32767).astype(np.int32)
        logits = np.zeros(n_act, dtype=np.float64)
        for j in range(n_act):
            acc = 0
            for k in range(h2):
                acc += int(wa_q[j, k]) * int(y2q[k])
            logits[j] = float(acc) * sa * inv_q + float(ba[j])
        return logits.astype(np.float32)

    lf = forward_fp(obs)
    lq = forward_q(obs)
    err = float(np.max(np.abs(lf - lq)))
    print(f"export_policy sanity max|logit_fp - logit_q| = {err:.4f}")


if __name__ == "__main__":
    raise SystemExit("import from train.py")
